package com.project.entities;
//Generated Aug 22, 2020, 3:23:46 PM by Hibernate Tools 5.4.18.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail_main",catalog="fishingworld")
public class OrderDetail implements java.io.Serializable {

	private static final long serialVersionUID = 8698619648286741870L;
	
	private OrderDetailId orderDetailId;
	private Order order;
	private Product product;
	private int quantity;
	private float amount;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId orderDetailId, Order order, Product product, int quantity, long amount) {
		this.orderDetailId = orderDetailId;
		this.order = order;
		this.product = product;
		this.quantity = quantity;
		this.amount = amount;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "order_id", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "product_id", column = @Column(name = "product_id", nullable = false)) })
	public OrderDetailId getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(OrderDetailId orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "amount", nullable = false, length = 15)
	public float getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

}
